"""Initial migration: create connections and tenants tables

Revision ID: b350bf4bd660
Revises: 
Create Date: 2026-02-03 12:43:12.051630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b350bf4bd660'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('software', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('token_created_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_id'), 'connections', ['id'], unique=False)
    op.create_index(op.f('ix_connections_software'), 'connections', ['software'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('tenant_name', sa.String(), nullable=False),
    sa.Column('xero_connection_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_connection_id'), 'tenants', ['connection_id'], unique=False)
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    
    # Create payroll_risk_analyses table if it doesn't exist (for fresh databases)
    # Check if table exists by trying to query it
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = inspector.get_table_names()
    
    if 'payroll_risk_analyses' not in tables:
        # Create the table for fresh databases
        op.create_table('payroll_risk_analyses',
            sa.Column('id', sa.String(), nullable=False),
            sa.Column('connection_id', sa.String(), nullable=False),
            sa.Column('connection_name', sa.String(), nullable=False),
            sa.Column('tenant_id', sa.String(), nullable=True),
            sa.Column('tenant_name', sa.String(), nullable=True),
            sa.Column('status', sa.String(), nullable=False),
            sa.Column('initiated_at', sa.String(), nullable=False),
            sa.Column('completed_at', sa.String(), nullable=True),
            sa.Column('result_data', sa.Text(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('progress', sa.Integer(), nullable=True, server_default='0'),
            sa.Column('progress_message', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        # Create initial indexes
        op.create_index('idx_connection_id', 'payroll_risk_analyses', ['connection_id'], unique=False)
        op.create_index('idx_status', 'payroll_risk_analyses', ['status'], unique=False)
        op.create_index('idx_initiated_at', 'payroll_risk_analyses', ['initiated_at'], unique=False)
    else:
        # Table exists, just alter columns (TEXT and String() are equivalent in PostgreSQL)
        # The column type changes are harmless but kept for consistency
        op.alter_column('payroll_risk_analyses', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        op.alter_column('payroll_risk_analyses', 'connection_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        op.alter_column('payroll_risk_analyses', 'connection_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        op.alter_column('payroll_risk_analyses', 'tenant_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        op.alter_column('payroll_risk_analyses', 'tenant_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        op.alter_column('payroll_risk_analyses', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        op.alter_column('payroll_risk_analyses', 'initiated_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
        op.alter_column('payroll_risk_analyses', 'completed_at',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        op.drop_index(op.f('idx_initiated_at'), table_name='payroll_risk_analyses')
        op.create_index('idx_initiated_at', 'payroll_risk_analyses', ['initiated_at'], unique=False)
    
    # Create additional indexes (whether table was just created or already existed)
    # Use IF NOT EXISTS equivalent by checking if index exists
    try:
        op.create_index(op.f('ix_payroll_risk_analyses_connection_id'), 'payroll_risk_analyses', ['connection_id'], unique=False)
    except Exception:
        pass  # Index might already exist
    try:
        op.create_index(op.f('ix_payroll_risk_analyses_id'), 'payroll_risk_analyses', ['id'], unique=False)
    except Exception:
        pass  # Index might already exist
    try:
        op.create_index(op.f('ix_payroll_risk_analyses_initiated_at'), 'payroll_risk_analyses', ['initiated_at'], unique=False)
    except Exception:
        pass  # Index might already exist
    try:
        op.create_index(op.f('ix_payroll_risk_analyses_status'), 'payroll_risk_analyses', ['status'], unique=False)
    except Exception:
        pass  # Index might already exist
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_risk_analyses_status'), table_name='payroll_risk_analyses')
    op.drop_index(op.f('ix_payroll_risk_analyses_initiated_at'), table_name='payroll_risk_analyses')
    op.drop_index(op.f('ix_payroll_risk_analyses_id'), table_name='payroll_risk_analyses')
    op.drop_index(op.f('ix_payroll_risk_analyses_connection_id'), table_name='payroll_risk_analyses')
    op.drop_index('idx_initiated_at', table_name='payroll_risk_analyses')
    op.create_index(op.f('idx_initiated_at'), 'payroll_risk_analyses', [sa.literal_column('initiated_at DESC')], unique=False)
    op.alter_column('payroll_risk_analyses', 'completed_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payroll_risk_analyses', 'initiated_at',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payroll_risk_analyses', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payroll_risk_analyses', 'tenant_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payroll_risk_analyses', 'tenant_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('payroll_risk_analyses', 'connection_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payroll_risk_analyses', 'connection_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('payroll_risk_analyses', 'id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # Note: Not dropping 'party' table as it may be used by other systems
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_connection_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_connections_software'), table_name='connections')
    op.drop_index(op.f('ix_connections_id'), table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
