"""Add MCP data cache table

Revision ID: e83d4d45b357
Revises: b350bf4bd660
Create Date: 2026-02-03 13:32:18.081984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83d4d45b357'
down_revision: Union[str, Sequence[str], None] = 'b350bf4bd660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_data_cache',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('cache_key', sa.String(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('cached_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cached_at', 'mcp_data_cache', ['cached_at'], unique=False)
    op.create_index('idx_connection_tenant_key', 'mcp_data_cache', ['connection_id', 'tenant_id', 'cache_key'], unique=True)
    op.create_index(op.f('ix_mcp_data_cache_cache_key'), 'mcp_data_cache', ['cache_key'], unique=False)
    op.create_index(op.f('ix_mcp_data_cache_cached_at'), 'mcp_data_cache', ['cached_at'], unique=False)
    op.create_index(op.f('ix_mcp_data_cache_connection_id'), 'mcp_data_cache', ['connection_id'], unique=False)
    op.create_index(op.f('ix_mcp_data_cache_id'), 'mcp_data_cache', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_data_cache_tenant_id'), 'mcp_data_cache', ['tenant_id'], unique=False)
    # Note: Not dropping 'party' table as it may be used by other systems
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Not recreating 'party' table as it may be used by other systems
    op.drop_index(op.f('ix_mcp_data_cache_tenant_id'), table_name='mcp_data_cache')
    op.drop_index(op.f('ix_mcp_data_cache_id'), table_name='mcp_data_cache')
    op.drop_index(op.f('ix_mcp_data_cache_connection_id'), table_name='mcp_data_cache')
    op.drop_index(op.f('ix_mcp_data_cache_cached_at'), table_name='mcp_data_cache')
    op.drop_index(op.f('ix_mcp_data_cache_cache_key'), table_name='mcp_data_cache')
    op.drop_index('idx_connection_tenant_key', table_name='mcp_data_cache')
    op.drop_index('idx_cached_at', table_name='mcp_data_cache')
    op.drop_table('mcp_data_cache')
    # ### end Alembic commands ###
